name: Repository Information

on:
  push:
    branches: -master

jobs:
  read-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read repository info
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Repository Name: ${repo.name}`);
            console.log(`Repository Owner: ${repo.owner.login}`);
            console.log(`Repository URL: ${repo.html_url}`);
            console.log(`Default Branch: ${repo.default_branch}`);
